### ISSUE TITLE
Mass assign error on players join table

### ISSUE THREAD

**Issue by rsung26** [estreske/Balderdash#1]
new_player = Player.create(user:test)
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: user
from /home/rsung/.rvm/gems/ruby-2.0.0-p353@block_rails_3/gems/activemodel-3.2.16/lib/active_model/mass_assignment_security/sanitizer.rb:48:in `process_removed_attributes'

**Comment by MikeSofaer** [comment]
console needed to be reloaded
